services:
  nginx:
    build:
      context: ./nginx/
    ports:
      - 3000:80
    volumes:
      - ./nginx/app/:/usr/share/nginx/html/app/
      - ./nginx/conf.d/:/etc/nginx/conf.d/
  # dns:
  #   build: 
  #     context: ./dns/
  #   restart: always
  #   ports:
  #     - 53:53
  #     - 53:53/udp
  #   volumes:
  #     - ./dns/named.conf:/etc/bind/named.conf
  #     - ./dns/zones/:/etc/bind/zones/
  #   command: named -c /etc/bind/named.conf -g -u named
