services:

## frontend of the goals app
  fontend:
    build: 
      context: ./frontend
    container_name: goals-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/package-lock.json  

## Backend of the goals app
  backend:
    build: 
      context: ./backend
    container_name: goals-backend
    ports:
      - "80:80"
    volumes:
      - ./backend:/app
      - /app/node_modules
      - /app/package-lock.json

