networks:
  goals-multi-cont-net:
    external: true


services:

## frontend of the goals app
  fontend:
    build: 
      context: ./frontend
    container_name: goals-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - goals-multi-cont-net

## Backend of the goals app
  backend:
    build: 
      context: ./backend
    container_name: goals-backend
    ports:
      - "80:80"
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - goals-multi-cont-net


## Database support for the goals app
  mongodb:
    image: mongo
    container_name: mongodb
    networks:
      - goals-multi-cont-net
    restart: always